import Navbar from './components/Navbar'
import Introduction from './components/Introduction'

function App() {
    return (
        <>
            <div className="w-screen h-screen overflow-x-hidden bg-slate-100 selection:bg-zinc-800 selection:text-zinc-50">
                <Navbar />
                <Introduction />
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil cumque ipsum eligendi quo hic nesciunt, repudiandae debitis optio distinctio quibusdam laborum corrupti aspernatur eveniet! Magni, inventore! Laborum corporis sapiente reprehenderit.
                Vitae expedita architecto blanditiis totam? Maxime amet laudantium est cumque laboriosam veniam et deserunt suscipit culpa neque, soluta praesentium minus quae rerum porro voluptate excepturi nam atque? Vitae, earum minima.
                Perspiciatis dolor tempora sunt natus provident, vitae cum? Recusandae dolores corrupti quo neque dicta eaque a doloremque quae ab sapiente, est ipsum architecto repudiandae consequatur commodi! Unde tempora pariatur tenetur.
                Eius, recusandae temporibus minima nulla amet laborum enim consequatur vitae voluptate? Magni vel quaerat quos vero doloremque fuga. Perferendis nam mollitia neque quod facere necessitatibus. Explicabo distinctio enim cumque nostrum!
                Amet quae quo distinctio delectus unde ab illum, tempore error. Totam corporis sunt, explicabo distinctio vero rem soluta quibusdam id dolores voluptatibus ea veritatis perferendis sit animi fugiat laboriosam modi?
                Ducimus eos eligendi sint voluptatum officia nemo soluta? Voluptas cum ullam animi temporibus dolorem facilis alias, tempore aperiam maxime. Assumenda odio pariatur itaque eius nobis officia aspernatur minima laborum ea!
                Voluptas suscipit voluptate earum consectetur, delectus odit eligendi distinctio nostrum, veritatis aliquam quidem error aperiam mollitia, ea amet sint? Sint quidem rerum facere blanditiis itaque cum nobis numquam sed ducimus.
                Provident eveniet possimus nisi velit perspiciatis, dolore adipisci iste fugit accusantium quibusdam exercitationem autem in! Quas commodi illo, in corporis excepturi eius explicabo, inventore, nesciunt vero earum perspiciatis quia repellat.
                Porro vitae expedita aspernatur. Nobis nostrum ut hic excepturi repellendus qui asperiores pariatur exercitationem dolores consequuntur! Iusto aliquid, quibusdam unde dicta, iure itaque dignissimos ratione, laboriosam tenetur rerum cupiditate omnis.
                Beatae exercitationem obcaecati incidunt quisquam corrupti animi laudantium. Recusandae exercitationem modi ipsa unde officiis, deleniti soluta maiores, sunt quisquam commodi, maxime esse! Omnis dolores ullam adipisci nesciunt quam vel placeat.
                Alias, incidunt quidem autem tempore deleniti est, ullam exercitationem quod corporis cupiditate fugit consectetur accusamus omnis atque, vero tempora. Reprehenderit sunt at est tenetur eligendi a alias voluptatum dolor voluptate.
                Ducimus saepe dignissimos debitis fugit doloremque! Dignissimos, omnis est quasi vitae sint ratione neque ea unde minima quibusdam explicabo voluptas cupiditate, assumenda voluptatibus ad corrupti distinctio vero quo quas dolores?
                Ab optio ipsum, corporis aspernatur quam distinctio, tempora nemo delectus culpa possimus rem minima ut adipisci. Iste, minus aliquid. Voluptatibus doloremque ea tempore enim at doloribus aperiam accusamus ullam magnam!
                Provident quasi ratione illum dignissimos in et autem veritatis porro harum hic architecto labore quam mollitia, nemo corporis explicabo nesciunt voluptatibus velit eveniet quod est id nisi rerum. Fugiat, recusandae!
                Rerum quod, necessitatibus, voluptatum, reiciendis est assumenda dolore accusamus distinctio error quidem eum fugiat minus quos. Quibusdam ut veniam dicta corrupti corporis, commodi laboriosam natus sit aperiam in consequuntur nostrum!
                Asperiores optio quod aliquam vitae qui hic fugiat esse aperiam velit natus modi quam eius, nobis fuga amet distinctio iure delectus doloribus? Repudiandae dolorem ipsa totam harum est vero magnam?
                Fugiat, quas. Dignissimos tenetur consequatur illo odit iste, esse consectetur ab. Laboriosam, at nisi praesentium, labore pariatur mollitia delectus maiores quisquam ipsum, rerum quas vel eum minus sunt tempora animi?
                Odio, numquam perspiciatis, molestias recusandae maxime dignissimos quam esse quis alias veritatis reprehenderit exercitationem fugiat sapiente. Ipsa excepturi ducimus a officiis modi quo magnam consequatur illum! Iste esse quasi saepe.
                Voluptates beatae earum labore modi rem esse voluptate tempore a quisquam repellendus pariatur adipisci fugiat error neque maxime praesentium, recusandae iusto voluptatibus. Nemo aliquid vel ipsa sint aliquam doloremque amet!
                Omnis, vel cum. Earum libero harum quia rem. Fugiat qui fuga unde officia hic accusantium pariatur blanditiis? Tempora sequi sed, veniam asperiores sapiente culpa nihil doloribus reprehenderit molestias repudiandae placeat.
                Aspernatur explicabo, assumenda repellendus ducimus non voluptates inventore quo quae consequatur excepturi, sed laboriosam cum quibusdam vitae neque numquam nobis qui? Fuga dignissimos dolorum, unde maxime accusamus molestias. Quis, enim.
                Iusto voluptates, hic saepe sunt natus ad autem, quam labore aspernatur ipsam exercitationem explicabo, corrupti nostrum placeat aperiam provident? Minus nam harum magni, aperiam odit quibusdam quis blanditiis sint quo.
                Accusantium, nobis aspernatur, dolorum aliquam quibusdam molestiae error eius odio excepturi autem suscipit, quos ipsam tempora quas molestias corporis! Officiis voluptas optio quas quod ipsam maiores consectetur vero facilis voluptatum.
                Qui delectus odit possimus modi minima vel, omnis tempora ducimus expedita unde numquam ex voluptatem ipsam perferendis voluptatibus quia asperiores maiores totam eos. Ad nobis consectetur sequi, dolores omnis nisi?
                Tenetur tempore obcaecati eius est? Pariatur explicabo culpa, sequi aut magnam unde laboriosam natus tempore impedit rem vero magni? Eius suscipit ad asperiores doloribus delectus quis facere eos id ducimus?
                Ad, voluptas neque. At incidunt velit obcaecati magnam, soluta nisi. Libero, ea autem quisquam, molestiae accusantium possimus nemo quam quae quis, doloremque adipisci recusandae magni? Ratione modi nemo natus quidem.
                Beatae perspiciatis reprehenderit totam enim ab nulla nihil a iste accusantium ratione in atque, est ex. Quibusdam saepe rerum corrupti natus doloremque tempora ipsum sit quaerat beatae, velit nobis perferendis!
                Dolores, rem consectetur pariatur magni neque quo quos, consequuntur maiores quibusdam minus nesciunt quasi labore voluptates nihil rerum veniam cumque similique. Omnis officiis quia facilis, in delectus rem eaque quibusdam.
                Distinctio iste iure dicta facilis accusantium, optio architecto provident voluptate alias, tempore quas esse. Quisquam amet molestiae inventore nihil, excepturi necessitatibus minus! Dolore mollitia voluptate aspernatur nesciunt odio voluptatem molestias.
                Consequuntur reprehenderit ea nihil ipsa! Rem cupiditate sapiente itaque ipsa enim nemo esse cum facere! Expedita eaque aliquam ipsum pariatur explicabo harum dolorum rerum voluptates illum at. Temporibus, nostrum ea! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis non nam quis amet officia, totam incidunt et corrupti praesentium, reprehenderit quas similique id. Officiis totam voluptatem eos, adipisci ut voluptate.
                Quas eum eos sapiente dolorem aut placeat atque? Culpa consequatur incidunt ea, magni saepe autem. Cupiditate repellat deserunt ratione perspiciatis architecto praesentium corporis est, blanditiis voluptatibus recusandae consectetur harum impedit.
                Ab earum minus minima nesciunt cum obcaecati, architecto modi, vel id, eos sunt. Natus, sunt veniam assumenda quidem non nostrum quia laboriosam aperiam ex soluta harum saepe dignissimos quos aut.
                Vero, explicabo aliquid rem dolores, voluptatibus minima itaque fuga quam in autem ea eligendi doloremque fugiat veniam quo cumque reprehenderit ex quasi? Expedita nesciunt ipsum hic nemo dolor quaerat molestiae!
                Officiis consectetur inventore vel fugiat expedita quam voluptate quae corporis excepturi, nam magni mollitia dolorem impedit sequi eos tempora voluptates atque rem molestias aut? Optio est doloribus nemo veniam tempore!
                Aliquam ex animi officia dicta odio expedita cupiditate, perferendis eligendi nesciunt nemo, odit suscipit dolorum quia aut illum. Porro delectus animi vero quisquam dolore velit earum itaque laudantium eos perferendis.
                Magni cumque veniam deleniti nulla inventore. Magni ab ratione expedita velit at aspernatur deleniti voluptatem tenetur eos cum nam, laborum et, dolorum iure iusto minima? Fugit eligendi dolorem inventore ipsum!
                Eos, a nihil ipsam minima nemo beatae porro sunt mollitia, laborum aut eveniet atque eaque laudantium veniam consequuntur temporibus dolore nobis dignissimos maxime iste rem? Itaque atque dignissimos delectus est.
                Reiciendis eligendi doloremque debitis dignissimos voluptatum possimus saepe nesciunt rerum veritatis repellat aliquam molestias dicta sit ipsa voluptate, maxime quod. Magni perspiciatis atque dolorum quaerat iure veniam ratione a optio.
                Veniam deserunt quae aperiam ratione! Impedit voluptatem ad dolore veniam porro soluta magnam possimus rerum aspernatur dolor quae ullam quis vitae facere rem officiis maxime iure quibusdam, odit adipisci quidem!
                Atque iusto asperiores reiciendis excepturi aspernatur laboriosam doloremque officiis soluta animi? Asperiores, optio quod at iure magnam sequi ab adipisci sint ipsum, obcaecati veniam, eaque dolor quam sed! Quidem, cumque?
                Ipsam repudiandae commodi earum numquam sint possimus voluptatibus pariatur cum blanditiis. Accusamus repellat officia delectus officiis cumque minus reprehenderit, in voluptatem reiciendis obcaecati perferendis maiores soluta natus, temporibus sunt vero.
                Aut in sapiente dolorum exercitationem numquam ea corrupti velit accusamus, accusantium cumque unde adipisci corporis maxime! Quas velit, molestiae reiciendis, dolore debitis quos magnam saepe blanditiis doloribus dolor enim repellendus?
                In, odit aut, repellendus consequatur veniam perferendis magni quis est unde aspernatur quaerat quos impedit eaque qui facere iure a, explicabo nesciunt! Sunt ad aut sed vero sit ipsam dolore?
                Magnam labore eius voluptate qui id accusamus cumque beatae ut? Dolorum dolores itaque dolore blanditiis. Ipsum aliquam quia fuga recusandae vero velit eum modi corporis eius explicabo, quaerat accusamus harum.
                Quasi voluptatum beatae, atque non nobis minus odit illum cumque corporis asperiores officiis harum ut magnam alias eius eligendi officia aliquid vitae fugit aut quia tempore suscipit id. Architecto, iure.
                Exercitationem temporibus deleniti possimus, sequi, quaerat officiis, reiciendis dolorem sit rem architecto voluptatem? Sed velit eos laborum, similique delectus natus saepe qui explicabo eligendi labore cupiditate id reprehenderit ipsum minus?
                Consequuntur expedita accusantium cum eligendi? Delectus consectetur nemo nobis recusandae libero ipsam sint quia? Sint eveniet beatae deleniti eos. Suscipit, rerum quo. Voluptatibus suscipit beatae quisquam minima sunt sequi quas?
                Molestias veritatis adipisci consectetur hic, commodi, architecto minus incidunt minima reprehenderit quidem tenetur accusamus sit nam tempora inventore atque asperiores illum labore exercitationem pariatur doloribus quaerat deserunt facilis. Inventore, blanditiis?
                Eum modi, deleniti iste rerum earum corporis culpa aspernatur corrupti nesciunt est blanditiis nisi odit, consequuntur consectetur quis debitis magni, reprehenderit eveniet assumenda at fugiat qui officiis tempora suscipit! Nam?
                Vel laborum neque quibusdam mollitia voluptates perspiciatis! Aut quia eveniet ea fuga similique perspiciatis expedita dicta assumenda, eos voluptatibus rem accusantium eum amet, tempora soluta ex blanditiis aspernatur vel cum.
                Accusamus, vitae obcaecati? Alias ratione numquam quibusdam eius veritatis temporibus aperiam? Inventore ipsam quis nostrum voluptatum aperiam sint, fugit aliquid consequuntur temporibus placeat quisquam nemo, architecto ipsa quibusdam, cumque minus.
                Asperiores magnam obcaecati dicta praesentium assumenda ipsa reiciendis perspiciatis reprehenderit, illum tenetur. Sit et sapiente dolorum ipsam, deleniti, nobis impedit, delectus dicta quaerat in corporis iste. Quasi nobis dicta accusantium.
                Sint alias, nobis laboriosam maxime qui perspiciatis, placeat iure explicabo corporis tenetur rem omnis sed rerum recusandae deserunt quam neque quos, eligendi est odio repudiandae aspernatur quis commodi? Blanditiis, illo.
                Vitae magnam aut perferendis corporis excepturi provident, ratione voluptates eos quod, nostrum ducimus asperiores sit vel quas! Dolores porro enim suscipit tempore sunt, dignissimos similique, quia fugiat modi labore et.
                Debitis, esse quidem. Deleniti, fugiat. Eius porro saepe sint ipsa aperiam natus, distinctio facilis mollitia neque, rem quisquam? Accusamus esse libero ab aliquam dolorum cupiditate quaerat in aperiam similique. Porro.
                Maxime, officia ab excepturi nisi nulla est commodi laboriosam accusamus eos omnis qui nam similique minus reiciendis perferendis fuga cumque odio soluta eius ut quae repellat labore voluptatibus. Alias, sint!
                Dolorem laboriosam atque rem expedita suscipit quam, animi eum debitis voluptates reprehenderit deleniti doloremque eos sed similique nostrum optio praesentium repellendus nemo. Quia esse aperiam asperiores voluptate voluptatibus. Quibusdam, voluptatum?
                Exercitationem quia cum corrupti dolorum. Porro sunt sapiente voluptatum similique voluptates. Similique deleniti quas esse architecto delectus nihil, itaque aspernatur, hic tenetur aliquam totam modi minima asperiores, omnis rerum ut.
                Esse aperiam ipsum veritatis dolores itaque. Quaerat deleniti esse enim quam dolor optio, ex corrupti quod dolore tempora, magni eaque iusto amet repudiandae tenetur veniam quis nesciunt itaque laudantium beatae!
                Voluptatibus excepturi optio quas nobis, beatae temporibus, ipsam corporis quod dolores quidem voluptatum eligendi enim doloremque dolore sapiente in non fugiat assumenda numquam voluptate similique iste quo. Repellat, soluta tempore?
                Beatae aliquid vitae non soluta consequatur molestias vero repellendus eos, labore fuga et itaque, iste pariatur quod doloremque sequi obcaecati aspernatur aperiam inventore fugiat corrupti corporis laboriosam! Culpa, aspernatur quaerat!
                Minus, amet nesciunt praesentium voluptate nulla sed quisquam perspiciatis blanditiis excepturi quod unde corporis doloremque perferendis odio iure sit eligendi repellat in dolorum dolorem, laboriosam rerum aperiam ipsum asperiores. Expedita!
                Voluptate impedit eum, in adipisci dignissimos consequatur mollitia perferendis earum, fugit sit eligendi excepturi unde. Nemo quis doloribus nulla commodi aspernatur. Iusto iure sint blanditiis eos officiis maxime modi eveniet?
                Repellat voluptatibus itaque quo architecto excepturi at. Quos est sunt animi iure. Tempora dolorum laboriosam quisquam ullam quibusdam obcaecati, fuga aperiam quasi accusantium, possimus repellat eaque? Eius quo repudiandae ut.
                Neque itaque eveniet molestias modi autem non! Cum, temporibus consequatur ratione dolores, consequuntur officiis quo inventore beatae nam sint, ab deserunt nesciunt delectus facere amet hic mollitia facilis incidunt optio!
                Itaque beatae distinctio odit? Molestiae commodi obcaecati pariatur nam voluptatum excepturi sint optio, nihil nisi vero dicta alias. Quae nam pariatur magni dignissimos distinctio perspiciatis odio delectus libero quibusdam temporibus.
                Fugit praesentium culpa dolorem pariatur ullam. Repellendus quia molestias saepe unde possimus assumenda et sapiente consequatur magnam corporis? Omnis repellendus optio quia asperiores nesciunt eum magnam ipsam suscipit nisi temporibus.
                Odio error illo enim sapiente exercitationem. Praesentium quae, nam animi ducimus voluptatem eos totam vel facere ipsa repellat amet sapiente quo ipsum molestias quidem alias repudiandae vero assumenda itaque minus.
                Alias dolorum commodi nihil laudantium sint, iusto vitae soluta modi, ex, ducimus distinctio. Similique explicabo sint saepe maxime, assumenda, eum nihil, dolorem obcaecati omnis neque unde? Vel saepe dolore deleniti.
                Quo modi commodi eos. Maiores maxime, a harum quo inventore veniam cumque repellat sunt distinctio odit eum quam eligendi suscipit id cum voluptatum aspernatur atque officiis voluptates animi ratione quis.
                Officiis exercitationem molestiae vel veniam suscipit quo rem dolorem non, perferendis voluptatibus a. Eum explicabo animi exercitationem alias voluptates veritatis maxime odio dolore veniam, quae corrupti fugit nam doloremque in?
                Corrupti, eligendi! Illo dolores, quo modi voluptatem inventore accusamus omnis at qui praesentium. Quaerat velit dolor maiores reiciendis dicta a, possimus magni nostrum ipsum. Minus blanditiis harum ipsum illum quia!
                Nesciunt fuga quos voluptate perferendis dolorem. Sint nobis tenetur maiores delectus vel vitae molestias qui, doloremque similique saepe, consequatur nulla aperiam et blanditiis, facilis doloribus eum. Mollitia voluptatum consequatur laborum!
                Architecto, adipisci amet. Exercitationem, dicta? Nihil quia, fuga earum tempore omnis nostrum adipisci quidem corporis eveniet provident dolorem est. Doloremque natus esse porro nulla rem impedit placeat debitis, non nostrum?
                Quod, incidunt. Recusandae libero minus quis unde exercitationem repellat, a laboriosam nihil rerum iure facere magni velit eum natus reiciendis cum odit, earum perferendis quasi molestias sed maxime? Provident, labore!
                Officia porro adipisci eligendi eum animi soluta. At quisquam odit fugit magni dolores inventore placeat vel sequi harum, laborum, quas eos eius eligendi eaque nam praesentium ea, quam incidunt natus.
                Reiciendis maiores ea porro unde voluptatibus eveniet et nemo sapiente impedit quas est libero hic dolorum saepe sit repellendus esse aspernatur doloremque modi, rem illum, suscipit, quasi enim. Quas, repellat!
                Accusamus dignissimos amet minima dolores repellat nisi incidunt corrupti eos autem quisquam voluptas ipsum ipsa minus, vitae laboriosam cupiditate in nostrum quaerat ullam ad! Laudantium id eos in nemo debitis?
                Consequatur, mollitia magni perferendis eaque tempora modi, dolore, id a hic quis corrupti veritatis repellat optio illo iste porro temporibus vero aliquam exercitationem recusandae alias laboriosam debitis. Necessitatibus, sint impedit.
            </div>
        </>
    )
}

export default App